apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-exporter
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: pg-exporter
  template:
    metadata:
      annotations:
      labels:
        app: pg-exporter
    spec:
      containers:
      - name: pg-exporter
        image: quay.io/prometheuscommunity/postgres-exporter:latest
        env:
        - name: DATA_SOURCE_NAME
          value: postgresql://postgres:postgres@paysera-postgresql-ha-pgpool.paysera.svc.cluster.local:5432/postgres?sslmode=disable
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - name: http
          containerPort: 9187
---
kind: Service
apiVersion: v1
metadata:
  name: pg-exporter
  namespace: monitoring
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "9187"
spec:
  selector:
    app: pg-exporter
  ports:
    - port: 9187
      targetPort: 9187
      protocol: TCP