serverFiles:
  alerting_rules.yml:
    groups:
    - name: Nodes monitoring
      rules:
      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Instance down (instance {{ $labels.instance }})"
          description: "A Prometheus target has disappeared. The instance is down or an exporter might be crashed.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - name: PostgreSQL
      rules:
      - alert: PostgresDown
        expr: pg_up == 0
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: Postgresql down (instance {{ $labels.instance }})

      - alert: PostgresTooManyConnections
        expr: sum by (instance, job, server) (pg_stat_activity_count) > min by (instance, job, server) (pg_settings_max_connections * 0.8)
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: Postgresql too many connections (instance {{ $labels.instance }})

      - alert: PostgresReplicationLag
        expr: pg_replication_lag_seconds > 5
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: Postgresql replication lag (instance {{ $labels.instance }})

      - alert: PostgresDiskUsage
        expr: pg_database_size_bytes > 100 * 1024 * 1024
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Database {{ $labels.datname }} is larger than 100 MB"
